import Head from "next/head";
import styled from "styled-components";
import SignIn from "../components/SignIn";

import styles from "../styles/Home.module.css";

const Center = styled.div`
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
`;
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>에코맵 관리자</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <SignIn />
      </Center>
      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
}
